Repository wro4j/wro4j, pull requests merged in 2023-09, with the labels that each got.

#1156 Issue #1155 - Maven plugin doesn't work due to 'contextFolder was not set' error
  pom.xml
  wro4j-maven-plugin/pom.xml
  wro4j-maven-plugin/src/main/java/ro/isdc/wro/maven/plugin/AbstractLinterMojo.java
  wro4j-maven-plugin/src/main/java/ro/isdc/wro/maven/plugin/AbstractSingleProcessorMojo.java
  wro4j-maven-plugin/src/main/java/ro/isdc/wro/maven/plugin/AbstractWro4jMojo.java
  wro4j-maven-plugin/src/main/java/ro/isdc/wro/maven/plugin/CssLintMojo.java
  wro4j-maven-plugin/src/main/java/ro/isdc/wro/maven/plugin/JsHintMojo.java
  wro4j-maven-plugin/src/main/java/ro/isdc/wro/maven/plugin/JsLintMojo.java
  wro4j-maven-plugin/src/main/java/ro/isdc/wro/maven/plugin/Wro4jMojo.java
  wro4j-osgi/pom.xml
Labels: bug

#1157 Issue #1131 - Switch dependency slf4j-log4j12 to slf4j-reload4j
  pom.xml
  wro4j-maven-plugin/pom.xml
Labels: dependencies

#1158 Issue #1049 - Add documentation explaining Wro4j's operating modes
  README.md
Labels: documentation

#1138 Update to commons-io 2.11.0
  pom.xml
  wro4j-core/src/main/java/ro/isdc/wro/model/resource/locator/UrlUriLocator.java
  wro4j-core/src/main/java/ro/isdc/wro/model/resource/locator/wildcard/DefaultWildcardStreamLocator.java
  wro4j-core/src/main/java/ro/isdc/wro/model/transformer/WildcardExpanderModelTransformer.java
Labels: dependencies

#1161 Fixed indentation issues in the README
  README.md
Labels: documentation

#1163 Issue #1162 - Wildcard webapp resources incorrectly resolved
  wro4j-core/src/main/java/ro/isdc/wro/model/transformer/WildcardExpanderModelTransformer.java
Labels: bug
